"""
╔══════════════════════════════════════════╗
║   ALERT: Email Notification             ║
║   Uses Gmail SMTP                       ║
╚══════════════════════════════════════════╝
"""

import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email                import encoders
from datetime             import datetime
from config import (
    EMAIL_ENABLED, EMAIL_SENDER, EMAIL_PASSWORD,
    EMAIL_RECEIVER, EMAIL_SMTP, EMAIL_PORT
)

log = logging.getLogger(__name__)


def send_email_alert(report: dict, pdf_path: str = None) -> dict:
    """Send email alert with scan report. Optionally attach PDF."""

    if not EMAIL_ENABLED:
        return {"status": "skipped", "reason": "Email alerts disabled in .env"}

    if not all([EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECEIVER]):
        return {"status": "error", "reason": "Email credentials not set in .env"}

    threat_level = report.get("threat_level", "UNKNOWN")
    target_type  = report.get("target_type", "unknown")
    scan_id      = report.get("scan_id", "N/A")
    ai_analysis  = report.get("ai_analysis", "No analysis available")

    subject = f"🚨 [{threat_level}] DARKWEB MONITOR Alert — {target_type.upper()} Scan | {scan_id}"

    # ── Build HTML email body ─────────────────────────
    color_map = {
        "CRITICAL": "#ff2020",
        "HIGH":     "#ff8c00",
        "MEDIUM":   "#ffe000",
        "LOW":      "#00cc44",
        "CLEAN":    "#00cc44"
    }
    color = color_map.get(threat_level, "#888888")

    html = f"""
    <html><body style="font-family: monospace; background: #0a0a0a; color: #e0e0e0; padding: 24px;">
      <div style="max-width:700px; margin:0 auto; border:1px solid #1a1a1a; padding:24px;">

        <h1 style="color:{color}; letter-spacing:3px; font-size:1.2rem;">
          ⚠ DARKWEB MONITOR — THREAT ALERT
        </h1>

        <table style="width:100%; border-collapse:collapse; margin:16px 0;">
          <tr><td style="color:#888; padding:6px 0; width:140px">Scan ID</td>
              <td style="color:#fff">{scan_id}</td></tr>
          <tr><td style="color:#888; padding:6px 0">Target Type</td>
              <td style="color:#fff">{target_type.upper()}</td></tr>
          <tr><td style="color:#888; padding:6px 0">Threat Level</td>
              <td style="color:{color}; font-weight:bold">{threat_level}</td></tr>
          <tr><td style="color:#888; padding:6px 0">Timestamp</td>
              <td style="color:#fff">{datetime.utcnow().isoformat()}</td></tr>
        </table>

        <hr style="border-color:#1a1a1a; margin:16px 0"/>

        <h2 style="color:#00ff41; font-size:0.9rem; letter-spacing:2px;">AI ANALYSIS</h2>
        <div style="background:#111; padding:16px; border-left:3px solid {color};
                    white-space:pre-wrap; font-size:0.85rem; line-height:1.6; color:#ccc;">
{ai_analysis}
        </div>

        <hr style="border-color:#1a1a1a; margin:16px 0"/>
        <p style="color:#444; font-size:0.75rem;">
          Generated by DARKWEB MONITOR — Automated Threat Intelligence System
        </p>
      </div>
    </body></html>
    """

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = EMAIL_SENDER
        msg["To"]      = EMAIL_RECEIVER
        msg.attach(MIMEText(html, "html"))

        # ── Attach PDF if provided ────────────────────
        if pdf_path:
            try:
                with open(pdf_path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename=threat_report_{scan_id}.pdf"
                    )
                    msg.attach(part)
                log.info(f"[EMAIL] PDF attached: {pdf_path}")
            except Exception as e:
                log.warning(f"[EMAIL] Could not attach PDF: {e}")

        # ── Send ──────────────────────────────────────
        with smtplib.SMTP(EMAIL_SMTP, EMAIL_PORT) as server:
            server.starttls()
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())

        log.info(f"[EMAIL] Alert sent to {EMAIL_RECEIVER}")
        return {"status": "sent", "recipient": EMAIL_RECEIVER}

    except smtplib.SMTPAuthenticationError:
        return {"status": "error", "reason": "Gmail auth failed. Use App Password not account password."}
    except Exception as e:
        log.error(f"[EMAIL] Send failed: {e}")
        return {"status": "error", "reason": str(e)}
